* * *



# Methods

RNA-seq counts were generated by [bcbio][] and [bcbioRNASeq][] using [salmon][] [@salmon]. Counts were imported into [R][] using [tximport][] [@tximport] and [DESeq2] [@DESeq2]. Gene annotations were obtained from [Ensembl][]. Plots were generated by [ggplot2][] [@ggplot2]. Heatmaps were generated by [pheatmap][] [@pheatmap].



# R session information

```{r sessionInfo}
sessionInfo()
```

```{r params}
# Print YAML parameters, if set
if (exists("params") & is(params, "knit_param_list")) {
    print(params)
}
```



[bcbio]: https://github.com/chapmanb/bcbio-nextgen
[bcbiornaseq]: http://bioinformatics.sph.harvard.edu/bcbioRNASeq
[bioconductor]: https://bioconductor.org
[deseq2]: https://bioconductor.org/packages/release/bioc/html/DESeq2.html
[ensembl]: http://useast.ensembl.org
[excel]: https://products.office.com/en-us/excel
[ggplot2]: http://ggplot2.org
[macos]: https://www.apple.com/macos
[pheatmap]: https://cran.r-project.org/web/packages/pheatmap/index.html
[r]: https://www.r-project.org
[rstudio]: https://www.rstudio.com
[salmon]: https://combine-lab.github.io/salmon
[tximport]: https://bioconductor.org/packages/release/bioc/html/tximport.html
[7-zip]: http://www.7-zip.org
