# Register S3 classes for use in S4 slots
# setOldClass("sessionInfo")



#' bcbioRnaDataSet
#'
#' S4 class containing RNA-seq counts and metadata generated by
#' [bcbio-nextgen](https://bcbio-nextgen.readthedocs.org/).
#'
#' `bcbioRnaDataSet` is a subclass of [SummarizedExperiment] designed to store
#' an RNA-seq analysis. This class contains experiment metadata, raw counts,
#' normalilzed counts, and summary statistics for each sample analyzed.
#'
#' Methods for this objects ...
#'
#' `metadata` contains ...
#'
#' @rdname bcbioRnaDataSet
#' @keywords internal
#' @aliases bcbioRnaDataSet-class
#' @export
bcbioRnaDataSet <- setClass(  # nolint
    "bcbioRnaDataSet",
    contains = "SummarizedExperiment",
    representation = representation(
        callers = "SimpleList",
        ensembl = "SimpleList"))
setValidity("bcbioRnaDataSet", function(object) TRUE)
