#' bcbioRNADataSet
#'
#' S4 class containing RNA-seq counts and metadata generated by
#' [bcbio-nextgen](https://bcbio-nextgen.readthedocs.org/).
#'
#' `bcbioRNADataSet` is a subclass of [SummarizedExperiment] designed to store
#' an RNA-seq analysis. This class contains raw read counts and transcripts per
#' million (TPM) generated by [tximport()].
#'
# Additional slots can be defined by setting the representation, if necessary.
# This is useful for including alternate count matrices (e.g. featureCounts)
# that don't necessarily match colData and rowData defined in the
# SummarizedExperiment.
#'
#' The `metadata` accessor contains:
#'
#' - Sample summary statistics (a.k.a. metrics).
#' - Ensembl annotations.
#' - Server run paths.
#' - R local environment information, including [sessionInfo()].
#'
#' @rdname bcbioRNADataSet
#' @export
bcbioRNADataSet <- setClass(  # nolint
    "bcbioRNADataSet",
    contains = "SummarizedExperiment",
    representation = representation(callers = "SimpleList"))
setValidity("bcbioRNADataSet", function(object) TRUE)
