#' bcbioRNASeq Object Class
#'
#' S4 class containing RNA-seq counts and metadata generated by
#' [bcbio](https://bcbio-nextgen.readthedocs.org/).
#'
#' `bcbioRNASeq` is a subclass of `SummarizedExperiment` designed to store
#' an RNA-seq analysis. This class contains raw read counts and transcripts per
#' million (TPM) generated by [tximport()].
#'
# Additional slots can be defined by setting the representation, if necessary.
# This is useful for including alternate count matrices (e.g. featureCounts).
#'
#' The `metadata` accessor contains:
#'
#' - Sample summary statistics (a.k.a. metrics).
#' - Ensembl annotations.
#' - Server run paths.
#' - R local environment information, including [sessionInfo()].
#'
#' @slot bcbio [SimpleList] containing additional bcbio run data with dimensions
#' that don't match the count matrix. This is currently used to store STAR
#' featureCounts aligned counts.
#'
#' @author Lorena Pantano, Michael Steinbaugh
#' @export
#'
#' @seealso
#' - [SummarizedExperiment::SummarizedExperiment].
#' - `.S4methods(class = "bcbioRNASeq")`.
#'
#' @examples
#' uploadDir <- system.file("extdata/bcbio", package = "bcbioRNASeq")
#'
#' # We're suppressing warnings about missing log files in our minimal
#' # dataset, which end up in the Travis CI logs. This isn't recommended
#' # for a typical bcbio run.
#' bcb <- suppressWarnings(loadRNASeq(uploadDir))
#' bcb
#'
#' # Check validity
#' validObject(bcb)
bcbioRNASeq <- setClass(
    "bcbioRNASeq",
    contains = "SummarizedExperiment",
    slots = c(bcbio = "SimpleList")
)



# Validity =====================================================================
#' @importFrom S4Vectors metadata
setValidity("bcbioRNASeq", function(object) {
    assert_is_all_of(object, "SummarizedExperiment")
    assert_has_dimnames(object)
    stopifnot(all(vapply(
        X = c(
            "assays",
            "bcbio",
            "colData",
            "elementMetadata",
            "metadata",
            "NAMES"
        ),
        FUN = function(slot) {
            .hasSlot(object, slot)
        },
        FUN.VALUE = logical(1L)
    )))

    # Metadata
    metadata <- metadata(object)
    requiredMetadata <- list(
        "version" = "package_version",
        "uploadDir" = "character",
        "sampleDirs" = "character",
        "projectDir" = "character",
        "template" = "character",
        "runDate" = "Date",
        "interestingGroups" = "character",
        "organism" = "character",
        "genomeBuild" = "character",
        # TODO Enforce version in future update
        "ensemblVersion" = c("numeric", "NULL"),
        # TODO Require data.frame in future update
        "annotable" = c("data.frame", "NULL"),
        "tx2gene" = "data.frame",
        "lanes" = c("integer", "numeric"),
        "yaml" = "list",
        "metrics" = "data.frame",
        "sampleMetadataFile" = c("character", "NULL"),
        "dataVersions" = "tbl_df",
        "programs" = "tbl_df",
        # Allowing `NULL` here for minimal working example
        # Otherwise Travis CI outputs the contents of log files
        "bcbioLog" = c("character", "NULL"),
        "bcbioCommandsLog" = c("character", "NULL"),
        "allSamples" = "logical",
        "design" = "formula",
        "transformationLimit" = c("integer", "numeric"),
        "date" = "Date",
        "wd" = "character",
        "utilsSessionInfo" = "sessionInfo",
        "devtoolsSessionInfo" = "session_info",
        "unannotatedGenes" = c("character", "NULL")
    )
    invisible(lapply(seq_along(requiredMetadata), function(a) {
        name <- names(requiredMetadata)[[a]]
        class <- requiredMetadata[[a]]
        assert_is_any_of(metadata[[name]], class)
    }))
    annotable <- metadata[["annotable"]]
    if (!is.null(annotable)) {
        assert_is_annotable(annotable)
    }
    tx2gene <- metadata[["tx2gene"]]
    assert_is_tx2gene(tx2gene)

    TRUE
})



# Legacy =======================================================================
#' bcbioRNADataSet Legacy Object Class
#'
#' This class has been superceded by [bcbioRNASeq] and will be formally
#' deprecated in a future release.
#'
#' @author Lorena Pantano, Michael Steinbaugh
#' @keywords internal
#'
#' @slot callers [SimpleList] containing additional bcbio run data with
#'   dimensions that don't match the count matrix.
#'
#' @export
bcbioRNADataSet <- setClass(
    "bcbioRNADataSet",
    contains = "SummarizedExperiment",
    slots = c(callers = "SimpleList")
)
setValidity("bcbioRNADataSet", function(object) TRUE)
