#' S4 Generics
#'
#' @rdname AllGenerics
#' @name AllGenerics
#' @keywords internal
#'
#' @param object Object.
#' @param i An integer or numeric scalar.
#' @param withDimnames A `logical`, indicating whether dimnames should be
#'   applied to extracted assay elements.
#' @param x Object.
#' @param ... Additional arguments.
#'
#' @return No value.
NULL



#' Quality Control Plots
#'
#' @rdname qcPlots
#' @name qcPlots
#' @keywords internal
#'
#' @param counts Counts matrix.
#' @param flip Flip X and Y axes.
#' @param interestingGroup *Optional*. Category to use to group samples (color
#'   and shape). If unset, this is automatically determined by the metadata set
#'   inside the [bcbioRNADataSet].
#' @param melted Melted counts generated by [meltLog10()].
#' @param metrics Metrics [data.frame] generated by [metrics()].
#' @param minCounts Numeric value for filtering the counts matrix before
#'   plotting.
#' @param normalized Count normalization method. See [counts()] documentation
#'   for more information.
#' @param passLimit Threshold to plot pass color marker.
#' @param warnLimit Threshold to plot warning color marker.
#'
#' @return [ggplot].
NULL



#' @rdname aggregateReplicates
#' @inheritParams AllGenerics
#' @export
setGeneric("aggregateReplicates", function(object, ...) {
    standardGeneric("aggregateReplicates")
})



#' @rdname alphaSummary
#' @inheritParams AllGenerics
#' @export
setGeneric("alphaSummary", function(object, ...) {
    standardGeneric("alphaSummary")
})



#' @rdname bcbio
#' @inheritParams AllGenerics
#' @export
setGeneric("bcbio", function(object, ...) {
    standardGeneric("bcbio")
})



#' @rdname bcbio
#' @inheritParams AllGenerics
#' @export
setGeneric("bcbio<-", function(object, ..., value) {
    standardGeneric("bcbio<-")
})



#' @rdname meltLog10
#' @inheritParams AllGenerics
#' @export
setGeneric("meltLog10", function(object, ...) {
    standardGeneric("meltLog10")
})



#' @rdname metadataTable
#' @inheritParams AllGenerics
#' @export
setGeneric("metadataTable", function(object, ...) {
    standardGeneric("metadataTable")
})



#' @rdname metrics
#' @inheritParams AllGenerics
#' @export
setGeneric("metrics", function(object) {
    standardGeneric("metrics")
})



#' @rdname plotCorrelationHeatmap
#' @inheritParams AllGenerics
#' @export
setGeneric("plotCorrelationHeatmap", function(object, ...) {
    standardGeneric("plotCorrelationHeatmap")
})



#' @rdname plotCountDensity
#' @inheritParams AllGenerics
#' @export
setGeneric("plotCountDensity", function(object, ...) {
    standardGeneric("plotCountDensity")
})



#' @rdname plotCountsPerGene
#' @inheritParams AllGenerics
#' @export
setGeneric("plotCountsPerGene", function(object, ...) {
    standardGeneric("plotCountsPerGene")
})



#' @rdname plotDEGHeatmap
#' @inheritParams AllGenerics
#' @export
setGeneric("plotDEGHeatmap", function(object, counts, ...) {
    standardGeneric("plotDEGHeatmap")
})



#' @rdname plotDispersion
#' @inheritParams AllGenerics
#' @export
setGeneric("plotDispersion", function(object) {
    standardGeneric("plotDispersion")
})



#' @rdname plotExonicMappingRate
#' @inheritParams AllGenerics
#' @export
setGeneric("plotExonicMappingRate", function(object, ...) {
    standardGeneric("plotExonicMappingRate")
})



#' @rdname plotGenderMarkers
#' @inheritParams AllGenerics
#' @export
setGeneric("plotGenderMarkers", function(object, ...) {
    standardGeneric("plotGenderMarkers")
})



#' @rdname plotGene
#' @inheritParams AllGenerics
#' @export
setGeneric("plotGene", function(object, ...) {
    standardGeneric("plotGene")
})



#' @rdname plotGeneDetectionSaturation
#' @inheritParams AllGenerics
#' @export
setGeneric("plotGeneDetectionSaturation", function(object, ...) {
    standardGeneric("plotGeneDetectionSaturation")
})



#' @rdname plotGeneHeatmap
#' @inheritParams AllGenerics
#' @export
setGeneric("plotGeneHeatmap", function(object, ...) {
    standardGeneric("plotGeneHeatmap")
})



#' @rdname plotGenesDetected
#' @inheritParams AllGenerics
#' @export
setGeneric("plotGenesDetected", function(object, ...) {
    standardGeneric("plotGenesDetected")
})



#' @rdname plotIntronicMappingRate
#' @inheritParams AllGenerics
#' @export
setGeneric("plotIntronicMappingRate", function(object, ...) {
    standardGeneric("plotIntronicMappingRate")
})



#' @rdname plotMA
#' @inheritParams AllGenerics
#' @export
setGeneric("plotMA", function(object, ...) {
    standardGeneric("plotMA")
})



#' @rdname plotMappedReads
#' @inheritParams AllGenerics
#' @export
setGeneric("plotMappedReads", function(object, ...) {
    standardGeneric("plotMappedReads")
})



#' @rdname plotMappingRate
#' @inheritParams AllGenerics
#' @export
setGeneric("plotMappingRate", function(object, ...) {
    standardGeneric("plotMappingRate")
})



#' @rdname plotMean_sd
#' @inheritParams AllGenerics
#' @export
setGeneric("plotMeanSD", function(object, ...) {
    standardGeneric("plotMeanSD")
})



#' @rdname plotMicroRNACounts
#' @inheritParams AllGenerics
#' @export
setGeneric("plotMicroRNACounts", function(object, ...) {
    standardGeneric("plotMicroRNACounts")
})



#' @rdname plotPattern
#' @inheritParams AllGenerics
#' @export
setGeneric("plotPattern", function(object, ...) {
    standardGeneric("plotPattern")
})



#' @rdname plotPCA
#' @inheritParams AllGenerics
#' @export
setGeneric("plotPCA", function(object, ...) {
    standardGeneric("plotPCA")
})



#' @rdname plotPCACovariates
#' @inheritParams AllGenerics
#' @export
setGeneric("plotPCACovariates", function(object, ...) {
    standardGeneric("plotPCACovariates")
})



#' @rdname plot_rrna_mapping_rate
#' @inheritParams AllGenerics
#' @export
setGeneric("plot_rrna_mapping_rate", function(object, ...) {
    standardGeneric("plot_rrna_mapping_rate")
})



#' @rdname plotSizeDistribution
#' @inheritParams AllGenerics
#' @export
setGeneric("plotSizeDistribution", function(object, ...) {
    standardGeneric("plotSizeDistribution")
})



#' @rdname plot_srna_clusters
#' @inheritParams AllGenerics
#' @export
setGeneric("plot_srna_clusters", function(object, ...) {
    standardGeneric("plot_srna_clusters")
})



#' @rdname plotTotalReads
#' @inheritParams AllGenerics
#' @export
setGeneric("plotTotalReads", function(object, ...) {
    standardGeneric("plotTotalReads")
})



#' @rdname plotVolcano
#' @inheritParams AllGenerics
#' @export
setGeneric("plotVolcano", function(object, ...) {
    standardGeneric("plotVolcano")
})



#' @rdname plot53Bias
#' @inheritParams AllGenerics
#' @export
setGeneric("plot53Bias", function(object, ...) {
    standardGeneric("plot53Bias")
})



#' @rdname sampleDirs
#' @inheritParams AllGenerics
#' @export
setGeneric("sampleDirs", function(object) {
    standardGeneric("sampleDirs")
})



#' @rdname tmm
#' @inheritParams AllGenerics
#' @export
setGeneric("tmm", function(object) {
    standardGeneric("tmm")
})



#' @rdname tpm
#' @inheritParams AllGenerics
#' @export
setGeneric("tpm", function(object) {
    standardGeneric("tpm")
})



#' @rdname txi
#' @inheritParams AllGenerics
#' @export
setGeneric("txi", function(object) {
    standardGeneric("txi")
})
