#' S4 Generics
#'
#' @rdname all_generics
#' @name all_generics
#' @keywords internal
#'
#' @param object Object.
#' @param i An integer or numeric scalar.
#' @param withDimnames A `logical`, indicating whether dimnames should be
#'   applied to extracted assay elements.
#' @param x Object.
#' @param ... Additional arguments.
#'
#' @return No value.
NULL



#' Quality Control Plots
#'
#' @rdname qc_plots
#' @name qc_plots
#' @keywords internal
#'
#' @param counts Counts matrix.
#' @param flip Flip X and Y axes.
#' @param interesting_group *Optional*. Category to use to group samples (color
#'   and shape). If unset, this is automatically determined by the metadata set
#'   inside the [bcbioRNADataSet].
#' @param melted Melted counts generated by [melt_log10()].
#' @param metrics Metrics [data.frame] generated by [metrics()].
#' @param min_counts Numeric value for filtering the counts matrix before
#'   plotting.
#' @param normalized Count normalization method. See [counts()] documentation
#'   for more information.
#' @param pass_limit Threshold to plot pass color marker.
#' @param warn_limit Threshold to plot warning color marker.
#'
#' @return [ggplot].
NULL



#' @rdname aggregate_replicates
#' @inheritParams all_generics
#' @export
setGeneric("aggregate_replicates", function(object, ...) {
    standardGeneric("aggregate_replicates")
})



#' @rdname alpha_summary
#' @inheritParams all_generics
#' @export
setGeneric("alpha_summary", function(object, ...) {
    standardGeneric("alpha_summary")
})



#' @rdname bcbio
#' @inheritParams all_generics
#' @export
setGeneric("bcbio", function(object, ...) {
    standardGeneric("bcbio")
})



#' @rdname bcbio
#' @inheritParams all_generics
#' @export
setGeneric("bcbio<-", function(object, ..., value) {
    standardGeneric("bcbio<-")
})



#' @rdname melt_log10
#' @inheritParams all_generics
#' @export
setGeneric("melt_log10", function(object, ...) {
    standardGeneric("melt_log10")
})



#' @rdname metadata_table
#' @inheritParams all_generics
#' @export
setGeneric("metadata_table", function(object, ...) {
    standardGeneric("metadata_table")
})



#' @rdname metrics
#' @inheritParams all_generics
#' @export
setGeneric("metrics", function(object) {
    standardGeneric("metrics")
})



#' @rdname plot_correlation_heatmap
#' @inheritParams all_generics
#' @export
setGeneric("plot_correlation_heatmap", function(object, ...) {
    standardGeneric("plot_correlation_heatmap")
})



#' @rdname plot_count_density
#' @inheritParams all_generics
#' @export
setGeneric("plot_count_density", function(object, ...) {
    standardGeneric("plot_count_density")
})



#' @rdname plot_counts_per_gene
#' @inheritParams all_generics
#' @export
setGeneric("plot_counts_per_gene", function(object, ...) {
    standardGeneric("plot_counts_per_gene")
})



#' @rdname plot_deg_heatmap
#' @inheritParams all_generics
#' @export
setGeneric("plot_deg_heatmap", function(object, counts, ...) {
    standardGeneric("plot_deg_heatmap")
})



#' @rdname plot_dispersion
#' @inheritParams all_generics
#' @export
setGeneric("plot_dispersion", function(object) {
    standardGeneric("plot_dispersion")
})



#' @rdname plot_exonic_mapping_rate
#' @inheritParams all_generics
#' @export
setGeneric("plot_exonic_mapping_rate", function(object, ...) {
    standardGeneric("plot_exonic_mapping_rate")
})



#' @rdname plot_gender_markers
#' @inheritParams all_generics
#' @export
setGeneric("plot_gender_markers", function(object, ...) {
    standardGeneric("plot_gender_markers")
})



#' @rdname plot_gene
#' @inheritParams all_generics
#' @export
setGeneric("plot_gene", function(object, ...) {
    standardGeneric("plot_gene")
})



#' @rdname plot_gene_detection_saturation
#' @inheritParams all_generics
#' @export
setGeneric("plot_gene_detection_saturation", function(object, ...) {
    standardGeneric("plot_gene_detection_saturation")
})



#' @rdname plot_gene_heatmap
#' @inheritParams all_generics
#' @export
setGeneric("plot_gene_heatmap", function(object, ...) {
    standardGeneric("plot_gene_heatmap")
})



#' @rdname plot_genes_detected
#' @inheritParams all_generics
#' @export
setGeneric("plot_genes_detected", function(object, ...) {
    standardGeneric("plot_genes_detected")
})



#' @rdname plot_intronic_mapping_rate
#' @inheritParams all_generics
#' @export
setGeneric("plot_intronic_mapping_rate", function(object, ...) {
    standardGeneric("plot_intronic_mapping_rate")
})



#' @rdname plot_ma
#' @inheritParams all_generics
#' @export
setGeneric("plot_ma", function(object, ...) {
    standardGeneric("plot_ma")
})



#' @rdname plot_mapped_reads
#' @inheritParams all_generics
#' @export
setGeneric("plot_mapped_reads", function(object, ...) {
    standardGeneric("plot_mapped_reads")
})



#' @rdname plot_mapping_rate
#' @inheritParams all_generics
#' @export
setGeneric("plot_mapping_rate", function(object, ...) {
    standardGeneric("plot_mapping_rate")
})



#' @rdname plot_mean_sd
#' @inheritParams all_generics
#' @export
setGeneric("plot_mean_sd", function(object, ...) {
    standardGeneric("plot_mean_sd")
})



#' @rdname plot_mirna_counts
#' @inheritParams all_generics
#' @export
setGeneric("plot_mirna_counts", function(object, ...) {
    standardGeneric("plot_mirna_counts")
})



#' @rdname plot_pattern
#' @inheritParams all_generics
#' @export
setGeneric("plot_pattern", function(object, ...) {
    standardGeneric("plot_pattern")
})



#' @rdname plot_pca
#' @inheritParams all_generics
#' @export
setGeneric("plot_pca", function(object, ...) {
    standardGeneric("plot_pca")
})



#' @rdname plot_pca_covariates
#' @inheritParams all_generics
#' @export
setGeneric("plot_pca_covariates", function(object, ...) {
    standardGeneric("plot_pca_covariates")
})



#' @rdname plot_rrna_mapping_rate
#' @inheritParams all_generics
#' @export
setGeneric("plot_rrna_mapping_rate", function(object, ...) {
    standardGeneric("plot_rrna_mapping_rate")
})



#' @rdname plot_size_distribution
#' @inheritParams all_generics
#' @export
setGeneric("plot_size_distribution", function(object, ...) {
    standardGeneric("plot_size_distribution")
})



#' @rdname plot_srna_clusters
#' @inheritParams all_generics
#' @export
setGeneric("plot_srna_clusters", function(object, ...) {
    standardGeneric("plot_srna_clusters")
})



#' @rdname plot_total_reads
#' @inheritParams all_generics
#' @export
setGeneric("plot_total_reads", function(object, ...) {
    standardGeneric("plot_total_reads")
})



#' @rdname plot_volcano
#' @inheritParams all_generics
#' @export
setGeneric("plot_volcano", function(object, ...) {
    standardGeneric("plot_volcano")
})



#' @rdname plot_5_3_bias
#' @inheritParams all_generics
#' @export
setGeneric("plot_5_3_bias", function(object, ...) {
    standardGeneric("plot_5_3_bias")
})



#' @rdname sample_dirs
#' @inheritParams all_generics
#' @export
setGeneric("sample_dirs", function(object) {
    standardGeneric("sample_dirs")
})



#' @rdname tmm
#' @inheritParams all_generics
#' @export
setGeneric("tmm", function(object) {
    standardGeneric("tmm")
})



#' @rdname tpm
#' @inheritParams all_generics
#' @export
setGeneric("tpm", function(object) {
    standardGeneric("tpm")
})



#' @rdname txi
#' @inheritParams all_generics
#' @export
setGeneric("txi", function(object) {
    standardGeneric("txi")
})
