#' Prepare a DAVID results table for knit report
#'
#' @author Michael Steinbaugh
#'
#' @param david DAVID results list generated by \code{run_david}
#'
#' @return Cutoff chart kable
#' @export
david_table <- function(david) {
    name <- deparse(substitute(david))

    df <- david$cutoff_chart
    if (is.null(df)) {
        stop("david run had no significant enrichment")
    }

    df <- df %>%
        as.data.frame %>%
        remove_rownames %>%
        .[, c("category", "term", "count", "fdr")]

    # Truncate the terms so the table isn't too wide
    df$term <- str_trunc(df$term, side = "right", width = 60)

    # Display FDR in scientific notation
    df$fdr <- format(df$fdr, digits = 3, scientific = TRUE)

    # Set the caption
    caption <- paste(name,
                     "david",
                     "functional annotation",
                     sep = " : ")

    return(kable(df, caption = caption))
}
