globalVariables(".")
legacyMetricsCols <- c("name", "x53Bias")
packageVersion <- packageVersion("bcbioRNASeq")
requiredAssays <- c("counts", "tpm", "length")
validCallers <- c("salmon", "kallisto", "sailfish")
