# Modified from bcbio-rnaseq qc-summary tempalte
# https://github.com/roryk/bcbio.rnaseq/blob/master/resources/bcbio/qc-summary.template


#' Import salmon counts
#'
#' Import \code{bcbio-rnaseq} \code{salmon} count data run using
#' \code{tximport}
#'
#' @author Michael Steinbaugh
#'
#' @import readr
#' @import tximport
#' @importFrom utils read.csv
#'
#' @param bcbio bcbio run object
#' @param summary Summary data frame
#'
#' @return txi \code{tximport} count data generated by \code{salmon}
#' @export
#'
#' @examples
#' \dontrun{
#' import_sailfish(bcbio, summary)
#' }
import_salmon <- function(bcbio, summary) {
    if (!is.list(bcbio)) {
        stop("bcbio run object is required.")
    }
    if (!is.data.frame(summary)) {
        stop("Summary data frame is required.")
    }
    if (!file.exists(file.path(bcbio$project_dir, "tx2gene.csv"))) {
        stop("tx2gene.csv file not found.")
    }

    tx2gene <- file.path(bcbio$project_dir, "tx2gene.csv") %>%
        utils::read.csv(header = FALSE)

    # Parse the HPC salmon directories
    salmon_files <- dir(bcbio$final_dir) %>%
        .[. %in% summary$description] %>%
        file.path(bcbio$final_dir,
                  .,
                  "salmon",
                  "quant",
                  "quant.sf") %>%
        sort
    if (!length(salmon_files)) {
        stop("No salmon files were found.")
    }

    names(salmon_files) <- sort(summary$description)

    # Import the counts
    txi <- tximport::tximport(salmon_files,
                              type = "salmon",
                              tx2gene = tx2gene,
                              reader = readr::read_tsv,
                              countsFromAbundance = "lengthScaledTPM")
    save(txi, file = "data/txi.rda")

    return(txi)
}
