#' Markdown List of Results Files
#'
#' Enables looping of results contrast file links for RMarkdown.
#'
#' @rdname md_results_tables
#' @author Michael Steinbaugh
#' @keywords internal
#'
#' @param res_tbl List of results tables generated by [results_tables()].
#' @param dir Output directory.
#'
#' @return [writeLines()].
.md_results_tables <- function(res_tbl, dir) {
    if (!dir.exists(dir)) {
        stop("DE results directory missing")
    }
    all <- res_tbl[["all_file"]]
    deg <- res_tbl[["deg_file"]]
    deg_lfc_up <- res_tbl[["deg_lfc_up_file"]]
    deg_lfc_down <- res_tbl[["deg_lfc_down_file"]]
    writeLines(c(
        str_c("- [", all, "](", file.path(dir, all), "):"),
        "    All genes, sorted by [Ensembl][] identifier.",
        str_c("- [", deg, "](", file.path(dir, deg), "):"),
        "    Genes that pass the alpha (FDR) cutoff.",
        str_c("- [", deg_lfc_up, "](", file.path(dir, deg_lfc_up), "):"),
        "    Upregulated DEG; positive log2 fold change.",
        str_c("- [", deg_lfc_down, "](", file.path(dir, deg_lfc_down), "):"),
        "    Downregulated DEG; negative log2 fold change."))
}
