#' RNA-Seq SummarizedExperiment
#'
#' Contains counts generated by [tximport()], along with bcbio-nextgen
#' run metadata.
#'
#' @rdname SummarizedExperiment
#' @keywords internal
#'
#' @author Michael Steinbaugh
#'
#' @param txi tximport list.
#' @param colData Sample metadata.
#' @param rowData Ensembl gene annotations.
#' @param metadata Custom metadata.
#'
#' @return [SummarizedExperiment].
.SummarizedExperiment <- function(txi, colData, rowData, metadata = NULL) {
    message("Packaging counts into SummarizedExperiment")

    # tximport ----
    abundance <- txi[["abundance"]]
    counts <- txi[["counts"]]
    length <- txi[["length"]]
    counts_from_abundance <- txi[["countsFromAbundance"]]

    # Metadata ----
    if (is.null(metadata)) {
        metadata <- SimpleList()
    } else {
        metadata <- SimpleList(metadata)
    }
    metadata[["counts_from_abundance"]] <- counts_from_abundance

    # SummarizedExperiment ----
    SummarizedExperiment(
        assays = SimpleList(
            abundance = abundance,
            counts = counts,
            length = length),
        colData = colData,
        rowData = rowData[rownames(counts), ],
        metadata = metadata)
}
