#' RNA-Seq SummarizedExperiment
#'
#' Contains counts generated by [tximport()], along with bcbio-nextgen
#' run metadata.
#'
#' @rdname SummarizedExperiment
#' @keywords internal
#'
#' @author Michael Steinbaugh
#'
#' @param txi tximport list.
#' @param colData Sample metadata.
#' @param rowData Ensembl gene annotations.
#' @param metadata Custom metadata.
#'
#' @return [SummarizedExperiment].
.SummarizedExperiment <- function(txi, colData, rowData, metadata = NULL) {
    message("Packaging counts into SummarizedExperiment")

    # tximport ----
    abundance <- txi[["abundance"]]
    counts <- txi[["counts"]]
    length <- txi[["length"]]
    counts_from_abundance <- txi[["countsFromAbundance"]]

    # Metadata ----
    if (is.null(meta)) {
        meta <- SimpleList()
    } else if (class(meta) != "SimpleList") {
        meta <- as(meta, "SimpleList")
    }
    meta[["counts_from_abundance"]] <- counts_from_abundance

    # Prepare colData and rowData ----
    colData <- colData[colnames(counts), ]
    rownames(colData) <- colnames(counts)

    rowData <- rowData[rownames(counts), ]
    rownames(rowData) <- rownames(counts)
    # [TODO] How to handle deprecated Ensembl identifiers?
    # Examples: ENSMUSG00000029333, ENSMUSG00000035349, ENSMUSG00000042402

    if (!identical(rownames(rowData), rownames(counts))) {
        stop("Gene identifier mismatch")
    }

    # SummarizedExperiment ----
    SummarizedExperiment(
        assays = SimpleList(
            abundance = abundance,
            counts = counts,
            length = length),
        colData = colData,
        rowData = rowData,
        metadata = meta)
}
