#' RNA-Seq SummarizedExperiment
#'
#' Contains counts generated by [tximport()], along with bcbio-nextgen
#' run metadata.
#'
#' @rdname SummarizedExperiment
#' @keywords internal
#'
#' @author Michael Steinbaugh
#'
#' @param txi tximport list.
#' @param colData Sample metadata.
#' @param rowData Ensembl gene annotations.
#' @param metadata Optional list of arbitrary content.
#'
#' @return [SummarizedExperiment].
.SummarizedExperiment <- function(txi, colData, rowData, metadata) {
    # tximport list
    abundance <- txi[["abundance"]]
    counts <- txi[["counts"]]
    length <- txi[["length"]]
    counts_from_abundance <- txi[["countsFromAbundance"]]

    # Subset the Ensembl rowData by genes present in counts matrix
    rowData <- rowData[rownames(counts), ]

    # Metadata
    metadata[["counts_from_abundance"]] <- counts_from_abundance

    SummarizedExperiment(
        assays = SimpleList(
            abundance = abundance,
            counts = counts,
            length = length),
        colData = colData,
        rowData = rowData,
        metadata = metadata)
}
