#' Markdown List of Results Files
#'
#' Enables looping of results contrast file links for RMarkdown.
#'
#' @rdname mdResultsTables
#' @author Michael Steinbaugh
#' @keywords internal
#'
#' @param resTbl List of results tables generated by [resultsTables()].
#' @param dir Output directory.
#'
#' @return [writeLines()].
.mdResultsTables <- function(resTbl, dir) {
    if (!dir.exists(dir)) {
        stop("DE results directory missing")
    }
    all <- resTbl[["allFile"]]
    deg <- resTbl[["degFile"]]
    degLFCUp <- resTbl[["degLFCUpFile"]]
    degLFCDown <- resTbl[["degLFCDownFile"]]
    writeLines(c(
        paste0("- [", all, "](", file.path(dir, all), "):"),
        "    All genes, sorted by [Ensembl][] identifier.",
        paste0("- [", deg, "](", file.path(dir, deg), "):"),
        "    Genes that pass the alpha (FDR) cutoff.",
        paste0("- [", degLFCUp, "](", file.path(dir, degLFCUp), "):"),
        "    Upregulated DEG; positive log2 fold change.",
        paste0("- [", degLFCDown, "](", file.path(dir, degLFCDown), "):"),
        "    Downregulated DEG; negative log2 fold change."))
}
