#' Load bcbio-nextgen run
#'
#' Simply point to the YAML file generated by \code{bcbio-nextgen} in the final
#' upload directory of the run, and this function will take care of the rest. It
#' imports data and program versions, and imports the RNA-seq counts
#' automatically. When working in RStudio, we recommend connecting to the
#' \code{bcbio-nextgen} run directory as a remote connection over \code{sshfs}.
#'
#' @author Michael Steinbaugh
#'
#' @param upload_dir Path to final upload directory. This path is set when
#'   running \code{bcbio_nextgen -w template}.
#' @param analysis Analysis type (e.g. \code{rnaseq} or \code{srnaseq})
#' @param intgroup Character vector of interesting groups. First entry is used
#'   for plot colors during quality control (QC) analysis. Entire vector is used
#'   for PCA and heatmap QC functions.
#' @param metadata_file Custom metadata file to import. Otherwise defaults to
#'   sample metadata saved in the YAML file.
#' @param organism Organism name, following Ensembl/Biomart conventions. Must be
#'   lowercase and one word (e.g. hsapiens). This will be detected automatically
#'   for common reference genomes and normally does not need to be set.
#' @param read_counts Automatically read in the count data using
#'   \code{read_bcbio_counts()}
#'
#' @return \code{bcbio-nextgen} run object
#' @export
load_run <- function(
    upload_dir = "final",
    analysis = "rnaseq",
    intgroup = "description",
    metadata_file = NULL,
    organism = NULL,
    read_counts = TRUE) {
    upload_dir <- normalizePath(upload_dir)
    # Check connection to upload_dir
    if (!length(dir(upload_dir))) {
        stop("Final upload directory failed to load")
    }

    # Find most recent nested project_dir (normally only 1)
    pattern <- "^(\\d{4}-\\d{2}-\\d{2})_([^/]+)$"
    project_dir <- dir(upload_dir,
                       pattern = pattern,
                       full.names = FALSE,
                       recursive = FALSE) %>%
        sort %>% rev %>% .[[1]]
    if (!length(project_dir)) {
        stop("Project directory not found")
    }
    message(project_dir)
    project_dir <- file.path(upload_dir, project_dir)

    # Program versions
    message("Reading program versions...")
    programs <- file.path(project_dir, "programs.txt") %>%
        read_delim(",", col_names = c("program", "version"))

    # Data versions
    if (file.exists(file.path(project_dir, "data_versions.csv"))) {
        message("Reading data versions...")
        data_versions <- file.path(project_dir, "data_versions.csv") %>%
            read_csv(col_types = cols())
    } else {
        data_versions <- NULL
    }

    # Find the summary YAML file automatically
    yaml_file <- dir(project_dir, pattern = "*.yaml$", full.names = TRUE)
    if (length(yaml_file) != 1) {
        stop("Unsure which YAML file to use")
    }

    # Load the YAML summary file
    message(paste("YAML:", basename(yaml_file)))
    yaml <- read_yaml(yaml_file)

    # Obtain the samples (and their directories) from the YAML
    sample_names <- sapply(yaml$samples,
                            function(x) { x$description }) %>% sort
    sample_dirs <- file.path(upload_dir, sample_names)
    names(sample_dirs) <- sample_names

    # Organism class (used with Ensembl)
    if (is.null(organism)) {
        # Use the genome build of the first sample to match
        genome_build <- yaml$samples[[1]]$genome_build
        organism <- detect_organism(genome_build)
    }
    message(paste("Genome:", genome_build))
    message(paste("Organism:", organism))

    # Detect number of sample lanes, determine if split
    lane_pattern <- "_L(\\d{3})"
    if (any(str_detect(sample_dirs, lane_pattern))) {
        message("Sample lanes detected")
        lanes <- str_match(names(sample_dirs), lane_pattern) %>%
            .[, 2] %>% unique %>% length
    } else {
        lanes <- NULL
    }

    run <- list(
        yaml_file = yaml_file,
        yaml = yaml,
        analysis = analysis,
        upload_dir = upload_dir,
        project_dir = project_dir,
        run_date = as.Date(yaml$date),
        today_date = Sys.Date(),
        wd = getwd(),
        hpc = detect_hpc(),
        sample_dirs = sample_dirs,
        intgroup = intgroup,
        metadata_file = metadata_file,
        metadata = NULL,
        organism = organism,
        ensembl = NULL,
        ensembl_version = NULL,
        lanes = lanes,
        programs = programs,
        data_versions = data_versions,
        session_info = sessionInfo())

    # Store metadata
    if (!is.null(metadata_file)) {
        # Read from custom data frame
        run$metadata <- read_metadata(metadata_file, lanes = lanes)
    } else{
        # Read from YAML
        run$metadata <- read_bcbio_samples_yaml(run, keys = "metadata")
    }

    # Subset the sample_dirs by the metadata data frame
    run$sample_dirs <- run$sample_dirs[run$metadata$description]
    names(run$sample_dirs) %>% toString %>% message

    if (analysis == "rnaseq") {
        # Save Ensembl annotations
        run$ensembl <- ensembl_annotations(
            run,
            attributes = c("external_gene_name",
                           "description",
                           "gene_biotype"))
        run$ensembl_version <- listMarts() %>% .[1, 2]

        # Read counts using `tximport()`
        if (isTRUE(read_counts)) {
            run$txi <- read_bcbio_counts(run)
        }
    } else if (analysis == "srnaseq") {
        message("Automatic count import not yet supported for small RNA-seq")
    } else {
        stop("Unsupported analysis type")
    }

    check_run(run)
    return(run)
}
