#' Top Tables of Differential Expression Results
#'
#' @rdname topTables
#' @name topTables
#'
#' @param object DESeq2 results tables list generated by [resultsTables()].
#' @param n Number genes to report.
#' @param coding Whether to only return coding genes.
#'
#' @return Top table kables, for knit report.
#'
#' @examples
#' data(res)
#' resTbl <- resultsTables(res, write = FALSE)
#' topTables(resTbl)
NULL



# Methods ====
#' @rdname topTables
#' @export
setMethod("topTables", "list", function(
    object,
    n = 50L,
    coding = FALSE) {
    subsetTop <- function(df) {
        if (isTRUE(coding)) {
            df <- df %>%
                .[.[["broadClass"]] == "coding", ]
        }
        df %>%
            head(n = n) %>%
            rename(lfc = .data[["log2FoldChange"]]) %>%
            mutate(
                baseMean = round(.data[["baseMean"]]),
                lfc = format(.data[["lfc"]], digits = 3L),
                padj = format(.data[["padj"]],
                              digits = 3L,
                              scientific = TRUE),
                description = str_trunc(.data[["description"]],
                                        width = 50L)) %>%
            .[, c("ensgene", "baseMean", "lfc", "padj",
                  "symbol", "description")] %>%
            remove_rownames
    }

    up <- subsetTop(object[["degLFCUp"]])
    down <- subsetTop(object[["degLFCDown"]])

    # Captions
    contrastName <- object[["contrast"]]

    show(kable(
        up,
        caption = paste(contrastName, "(upregulated)")))
    show(kable(
        down,
        caption = paste(contrastName, "(downregulated)")))
})
