#' Top Tables of Differential Expression Results
#'
#' @rdname topTables
#' @name topTables
#' @author Michael Steinbaugh
#'
#' @param object DESeq2 results tables list generated by [resultsTables()].
#' @param n Number genes to report.
#' @param coding Whether to only return coding genes.
#'
#' @return Top table kables, for knit report.
#'
#' @examples
#' data(res)
#' resTbl <- resultsTables(res, write = FALSE)
#' topTables(resTbl)
NULL



# Constructors ====
.subsetTop <- function(df, n, coding) {
    if (isTRUE(coding)) {
        df <- df %>%
            .[.[["broadClass"]] == "coding", , drop = FALSE]
    }
    df <- df %>%
        head(n = n) %>%
        tidy_rename(lfc = .data[["log2FoldChange"]]) %>%
        mutate(
            baseMean = round(.data[["baseMean"]]),
            lfc = format(.data[["lfc"]], digits = 3L),
            padj = format(.data[["padj"]],
                          digits = 3L,
                          scientific = TRUE),
            # Remove symbol information in description, if present
            description = str_replace(.data[["description"]],
                                      " \\[.+\\]$",
                                      "")) %>%
        .[, c("ensgene", "baseMean", "lfc", "padj",
              "symbol", "description")] %>%
        remove_rownames %>%
        fixNA
}



# Methods ====
#' @rdname topTables
#' @export
setMethod("topTables", "list", function(
    object,
    n = 50L,
    coding = FALSE) {
    up <- .subsetTop(object[["degLFCUp"]], n = n, coding = coding)
    down <- .subsetTop(object[["degLFCDown"]], n = n, coding = coding)

    # Captions
    contrastName <- object[["contrast"]]

    show(kable(
        up,
        caption = paste(contrastName, "(upregulated)")))
    show(kable(
        down,
        caption = paste(contrastName, "(downregulated)")))
})
