#' Differential Expression Results Tables
#'
#' @rdname resultsTables
#' @name resultsTables
#'
#' @param res [DESeqResults].
#' @param lfc Log fold change ratio (base 2) cutoff. Does not apply to
#'   statistical hypothesis testing, only gene filtering in the results tables.
#'   See [results()] for additional information about using `lfcThreshold` and
#'   `altHypothesis` to set an alternative hypothesis based on expected fold
#'   changes.
#' @param write Write CSV files to disk.
#' @param dir Directory path where to write files.
#'
#' @return Results list.
#'
#' @examples
#' data(bcb, res)
#' resTbl <- resultsTables(bcb, res, lfc = 0.25, write = FALSE)
#' class(resTbl)
#' names(resTbl)
NULL



# Constructors ====
#' Markdown List of Results Files
#'
#' Enables looping of results contrast file links for RMarkdown.
#'
#' @rdname internal-mdResultsTables
#' @author Michael Steinbaugh
#' @keywords internal
#'
#' @param resTbl List of results tables generated by [resultsTables()].
#' @param dir Output directory.
#'
#' @return [writeLines()].
.mdResultsTables <- function(resTbl, dir) {
    if (!dir.exists(dir)) {
        stop("DE results directory missing")
    }
    all <- resTbl[["allFile"]]
    deg <- resTbl[["degFile"]]
    degLFCUp <- resTbl[["degLFCUpFile"]]
    degLFCDown <- resTbl[["degLFCDownFile"]]
    writeLines(c(
        paste0("- [", all, "](", file.path(dir, all), "):"),
        "    All genes, sorted by [Ensembl][] identifier.",
        paste0("- [", deg, "](", file.path(dir, deg), "):"),
        "    Genes that pass the alpha (FDR) cutoff.",
        paste0("- [", degLFCUp, "](", file.path(dir, degLFCUp), "):"),
        "    Upregulated DEG; positive log2 fold change.",
        paste0("- [", degLFCDown, "](", file.path(dir, degLFCDown), "):"),
        "    Downregulated DEG; negative log2 fold change."))
}



# Methods ====
#' @rdname resultsTables
#' @export
setMethod("resultsTables", "bcbioRNADataSet", function(
    object,
    res,
    lfc = 0L,
    write = TRUE,
    dir = file.path("results", "differential_expression")) {
    name <- deparse(substitute(res))
    contrast <- .resContrastName(res)
    fileStem <- paste(name,
                      str_replace_all(contrast, " ", "_"),
                      sep = "_")

    # Alpha level, from [DESeqResults]
    alpha <- metadata(res)[["alpha"]]
    annotations <- rowData(object) %>%
        as.data.frame

    all <- res %>%
        as.data.frame %>%
        rownames_to_column("ensgene") %>%
        as("tibble") %>%
        camel %>%
        left_join(annotations, by = "ensgene") %>%
        arrange(!!sym("ensgene"))

    # Check for overall gene expression with base mean
    baseMeanGt0 <- all %>%
        arrange(desc(!!sym("baseMean"))) %>%
        .[.[["baseMean"]] > 0L, ]
    baseMeanGt1 <- baseMeanGt0 %>%
        .[.[["baseMean"]] > 1L, ]

    # All DEG tables are sorted by BH adjusted P value
    deg <- all %>%
        .[!is.na(.[["padj"]]), ] %>%
        .[.[["padj"]] < alpha, ] %>%
        arrange(!!sym("padj"))
    degLFC <- deg %>%
        .[.[["log2FoldChange"]] > lfc |
              .[["log2FoldChange"]] < -lfc, ]
    degLFCUp <- degLFC %>%
        .[.[["log2FoldChange"]] > 0L, ]
    degLFCDown <- degLFC %>%
        .[.[["log2FoldChange"]] < 0L, ]

    # File paths
    allFile <- paste(fileStem, "all_genes.csv.gz", sep = "_")
    degFile <- paste(fileStem, "deg.csv.gz", sep = "_")
    degLFCUpFile <- paste(fileStem, "deg_lfc_up.csv.gz", sep = "_")
    degLFCDownFile <- paste(fileStem, "deg_lfc_down.csv.gz", sep = "_")

    resTbl <- list(
        res = res,
        name = name,
        contrast = contrast,
        # Cutoffs
        alpha = alpha,
        lfc = lfc,
        # Tibbles
        all = all,
        deg = deg,
        degLFC = degLFC,
        degLFCUp = degLFCUp,
        degLFCDown = degLFCDown,
        # File paths
        allFile = allFile,
        degFile = degFile,
        degLFCUpFile = degLFCUpFile,
        degLFCDownFile = degLFCDownFile)

    writeLines(c(
        paste(name, "differential expression tables"),
        paste("-", nrow(all), "gene annotations"),
        "- cutoffs applied:",
        paste("    - alpha:", alpha),
        paste("    - lfc:  ", lfc, "(tables only)"),
        "- gene detection:",
        paste("    - base mean > 0:", nrow(baseMeanGt0), "genes"),
        paste("    - base mean > 1:", nrow(baseMeanGt1), "genes"),
        "- pass cutoffs:",
        paste("    - alpha:   ", nrow(deg), "genes"),
        paste("    - lfc up:  ", nrow(degLFCUp), "genes"),
        paste("    - lfc down:", nrow(degLFCDown), "genes")))

    if (isTRUE(write)) {
        # Write the CSV files
        dir.create(dir, recursive = TRUE, showWarnings = FALSE)
        write_csv(all, file.path(dir, allFile))
        write_csv(deg, file.path(dir, degFile))
        write_csv(degLFCUp, file.path(dir, degLFCUpFile))
        write_csv(degLFCDown, file.path(dir, degLFCDownFile))
        # Output file information in Markdown format
        .mdResultsTables(resTbl, dir)
    }

    resTbl
})
