#' Sample PCA Plot for Transformed Data
#'
#' Wrapper for [DESeq2::plotPCA()] that improves principal component analysis
#' (PCA) sample coloring and labeling.
#'
#' @name plotPCA
#' @author Michael Steinbaugh
#'
#' @importFrom BiocGenerics plotPCA
#'
#' @inheritParams general
#' @inheritParams counts
#' @inheritParams plotGene
#'
#' @param interestingGroups *Optional.* Interesting groups to use for point
#'   appearance. If missing, color defaults to all `interestingGroups`
#'   parameters set in the [bcbioRNASeq] object.
#' @param genes *Optional.* Character vector of gene identifiers to use.
#' @param censorSamples *Optional.* Samples to exclude from the PCA plot.
#'   Supply them as a character vector. These should match `colnames(object)`.
#' @param label *Optional.* Superimpose sample text labels on the plot.
#' @param returnData Return PCA loadings data instead of plotting.
#'
#' @seealso [DESeq2::plotPCA()].
#'
#' @return [ggplot].
#'
#' @examples
#' load(system.file("extdata/bcb.rda", package = "bcbioRNASeq"))
#'
#' # bcbioRNASeq
#' plotPCA(bcb, label = TRUE)
#' plotPCA(bcb, label = FALSE)
#'
#' # Default ggplot color palette
#' plotPCA(bcb, interestingGroups = "sampleName", color = NULL)
#'
#' # Censor samples
#' colnames(bcb)
#' censor <- "group1_1"
#' plotPCA(bcb, censorSamples = censor)
NULL



# Constructors =================================================================
#' @importFrom basejump camel
#' @importFrom ggplot2 aes_string coord_fixed geom_point ggplot guides labs
#' @importFrom ggrepel geom_text_repel
#' @importFrom grid arrow unit
.plotPCA.DESeqTransform <- function(  # nolint
    object,
    interestingGroups = "sampleName",
    genes = NULL,
    color = scale_color_viridis(discrete = TRUE),
    label = FALSE,
    returnData = FALSE) {
    assert_is_all_of(object, "DESeqTransform")
    assertFormalInterestingGroups(colData(object), interestingGroups)
    assertIsCharacterOrNULL(genes)
    assertIsColorScaleDiscreteOrNULL(color)
    assert_is_a_bool(label)
    assert_is_a_bool(returnData)

    # Subset genes, if desired
    if (is.null(genes)) {
        # Recommended DESeq default
        ntop <- 500L
        inform(paste(
            "Plotting PCA using top", ntop, "most variable genes"
        ))
    } else if (is.character(genes)) {
        object <- object[genes, , drop = FALSE]
        # Set ntop to the number of genes requested
        ntop <- length(genes)
        inform(paste(
            "Plotting PCA using", ntop, "genes"
        ))
    }

    # `group` column is generated by `plotPCA()` using `interestingGroups`
    data <- plotPCA(
        object,
        intgroup = interestingGroups,
        returnData = TRUE,
        ntop = ntop) %>%
        camel()

    percentVar <- round(100L * attr(data, "percentVar"))

    # Use `sampleName` for plot labels
    data[["label"]] <- colData(object)[, "sampleName", drop = TRUE]

    p <- ggplot(
        data,
        mapping = aes_string(
            x = "pc1",
            y = "pc2",
            color = "group")
    ) +
        geom_point(size = 4L) +
        coord_fixed() +
        labs(
            title = "pca",
            x = paste0("pc1: ", percentVar[[1L]], "% variance"),
            y = paste0("pc2: ", percentVar[[2L]], "% variance"),
            color = paste(interestingGroups, collapse = ":\n")
        )

    if (is(color, "ScaleDiscrete")) {
        p <- p + color
    }

    if (isTRUE(label)) {
        p <- p +
            geom_text_repel(
                # Color the labels to match the points
                aes_string(label = "label"),
                color = "black",
                fontface = "bold",
                # Add extra padding around each text label
                box.padding = unit(0.5, "lines"),
                # Add extra padding around each data point
                point.padding = unit(1.5, "lines"),
                # Color of the line segments
                segment.color = "gray",
                # Width of the line segments
                segment.size = 0.5,
                # Draw an arrow from the label to the data point
                arrow = arrow(length = unit(0.01, "npc")),
                # Strength of the repulsion force
                force = 1L,
                show.legend = FALSE)
    }

    if (isTRUE(returnData)) {
        data
    } else {
        p
    }
}



# Methods ======================================================================
#' @rdname plotPCA
#' @export
setMethod(
    "plotPCA",
    signature("bcbioRNASeq"),
    function(
        object,
        normalized = "rlog",
        interestingGroups,
        genes = NULL,
        censorSamples = NULL,
        color = scale_color_viridis(discrete = TRUE),
        label = FALSE,
        returnData = FALSE) {
        # Passthrough: genes, color, label, returnData
        if (missing(interestingGroups)) {
            interestingGroups <- bcbioBase::interestingGroups(object)
        }
        assert_is_any_of(censorSamples, c("character", "factor", "NULL"))

        # Obtain internal DESeqTransform
        dt <- assays(object)[[normalized]]
        if (!is(dt, "DESeqTransform")) {
            inform("Generating DESeqTransform from counts")
            counts <- counts(object, normalized = normalized)
            se <- SummarizedExperiment(
                assays = counts,
                colData = colData(object))
            dt <- DESeqTransform(se)
        }

        # Censor samples, if desired
        if (!is.null(censorSamples)) {
            assert_is_subset(censorSamples, colnames(object))
            samples <- setdiff(colnames(object), censorSamples)
            dt <- dt[, samples, drop = FALSE]
        }

        .plotPCA.DESeqTransform(
            dt,
            interestingGroups = interestingGroups,
            genes = genes,
            color = color,
            label = label,
            returnData = returnData
        )
    }
)
