#' Sample PCA Plot for Transformed Data
#'
#' Wrapper for [DESeq2::plotPCA()] that improves principal component analysis
#' (PCA) sample coloring and labeling.
#'
#' @rdname plot_pca
#' @author Michael Steinbaugh
#'
#' @param transform String specifying [rlog] (**recommended**) or [vst]
#'   [DESeqTransform] slotted inside the [bcbioRNADataSet].
#' @param genes *Optional*. Character vector of gene identifiers to use.
#' @param interesting_groups *Optional*. Interesting groups to use for point
#'   appearance. If `NULL`, color defaults to all `interesting_groups`
#'   parameters set in [bcbioRNADataSet].
#' @param shape *Optional*. Make points easier to inspect with differing shapes.
#' @param label *Optional*. Superimpose sample text labels on the plot.
#'
#' @seealso [DESeq2::plotPCA()].
#'
#' @return [ggplot].
#' @export
#'
#' @examples
#' data(bcb)
#' plot_pca(bcb)
setMethod("plot_pca", "bcbioRNADataSet", function(
    object,
    transform = "rlog",
    genes = NULL,
    interesting_groups = NULL,
    shape = FALSE,
    label = TRUE) {
    if (!transform %in% c("rlog", "vst")) {
        stop("DESeqTransform must be rlog or vst")
    }
    dt <- assays(object)[[transform]]

    # Subset genes, if desired
    if (!is.null(genes)) {
        dt <- dt[genes, ]
        # Set ntop to the number of genes requested
        ntop <- length(genes)
    } else {
        # Recommended DESeq default
        ntop <- 500L
    }

    # Interesting groups
    if (is.null(interesting_groups)) {
        interesting_groups <- metadata(object)[["interesting_groups"]]
    }
    interesting_groups_name <- paste(interesting_groups, collapse = ":\n")

    # `group` column is generated by `plotPCA()` using `interesting_groups`
    data <- plotPCA(dt,
                    intgroup = interesting_groups,
                    returnData = TRUE,
                    ntop = ntop) %>% snake
    percent_var <- round(100L * attr(data, "percentVar"))

    # Always define color by `interesting_groups`
    data[["color"]] <- data[["group"]]

    if (isTRUE(shape)) {
        data[["shape"]] <- data[["group"]]
    } else {
        data[["shape"]] <- "default"
    }

    data[["label"]] <- rownames(colData(dt))

    p <- ggplot(
        data,
        aes_(x = ~pc1,
             y = ~pc2,
             color = ~color,
             shape = ~shape)) +
        geom_point(size = 3L) +
        coord_fixed() +
        labs(title = "pca",
             x = paste0("pc1: ", percent_var[[1L]], "% variance"),
             y = paste0("pc2: ", percent_var[[2L]], "% variance"),
             color = interesting_groups_name,
             shape = interesting_groups_name)

    if (!isTRUE(shape)) {
        p <- p + guides(shape = FALSE)
    }

    # Show side by side if label is set
    if (isTRUE(label)) {
        unlabeled <- p +
            theme(legend.position = "none")
        labeled <- p +
            geom_text_repel(aes_(label = ~label), show.legend = FALSE) +
            labs(title = "", x = "", y = "") +
            theme(axis.text.x = element_blank(),
                  axis.text.y = element_blank(),
                  axis.ticks.x = element_blank(),
                  axis.ticks.y = element_blank(),
                  legend.position = "bottom")
        plot_grid(unlabeled,
                  labeled,
                  nrow = 2L)
    } else {
        p
    }
})
