#' Quickly plot principal component analysis (PCA)
#'
#' @author Michael Steinbaugh
#'
#' @import DESeq2
#' @import ggplot2
#'
#' @param dt \code{DESeqTransform} object generated from \code{rlog()} or
#'   \code{vst()} on a \code{DESeqDataSet} object. We prefer to pipe the
#'   transformed data in to this function because the operation is CPU
#'   intensive, and is slow when applied to multiple PCA plot operations.
#' @param factor PCA factor groups for \code{DESeq2::plotPCA()}. Shapes are
#'   defined by the first value.
#' @param ... Passthrough to \code{DESeq2::plotPCA()}.
#'
#' @return PCA plot
#' @export
#'
#' @examples
#' \dontrun{
#' plot_deseq_pca(rlog)
#' }
plot_deseq_pca <- function(
    dt,
    factor = c("group"),
    ...) {
    if (class(dt)[1] != "DESeqTransform") {
        stop("This function requires a DESeqTransform object.")
    }
    name <- deparse(substitute(dt))
    data <- dt %>%
        # `plotPCA()` uses `ntop = 500` by default
        # To plot all gene variation, use `ntop = nrow(.)`
        DESeq2::plotPCA(intgroup = factor,
                        returnData = TRUE,
                        ...)
    percent_var <- round(100 * attr(data, "percentVar"))
    # The `group` column is generated by `plotPCA()` with `intgroup`.
    color <- "group"
    shape <- factor[1]
    data.frame(PC1 = data$PC1,
               PC2 = data$PC2,
               color = data[[color]],
               shape = data[[shape]]) %>%
        ggplot2::ggplot(
            ggplot2::aes_(x = ~PC1,
                          y = ~PC2,
                          color = ~color,
                          shape = ~shape)
        ) +
        ggplot2::ggtitle(paste("pca:", name)) +
        ggplot2::geom_point(size = 3) +
        ggplot2::xlab(paste0("pc1: ", percent_var[1], "% variance")) +
        ggplot2::ylab(paste0("pc2: ", percent_var[2], "% variance")) +
        ggplot2::coord_fixed() +
        ggplot2::labs(color = color, shape = shape)
}
