# [fix] Look at incorporating [plotCounts()] into this function.
#' Plot an individual gene
#'
#' @author Michael Steinbaugh
#'
#' @param bcb [bcbioRnaDataSet].
#' @param normalized_counts Normalized counts matrix. Can be obtained from
#'   [DESeqDataSet] using [counts()] with `normalized = TRUE)`. Transcripts per
#'   million (TPM) are also acceptable.
#' @param gene Gene identifier. Can input multiple genes as a character vector.
#' @param format Ensembl identifier format. Defaults to the gene name (symbol).
#'
#' @export
plot_gene <- function(
    bcb,
    normalized_counts,
    gene,
    format = "external_gene_name") {
    run <- metadata(bcb)

    color <- run$interesting_groups[1]
    ylab <- deparse(substitute(normalized_counts))
    metadata <- run$metadata

    # Match unique gene identifier with name (gene symbol) using the internally
    # stored Ensembl annotations saved in the run object
    match <- run$ensembl %>%
        .[.[[format]] %in% gene, ] %>%
        .[order(.$external_gene_name), ]

    # Seq along Ensembl data frame here instead of the gene input vector,
    # which will then output only genes that match Ensembl
    lapply(1:nrow(match), function(a) {
        gene_name <- match$external_gene_name[[a]]
        gene_id <- match$ensembl_gene_id[[a]]
        plot <- data.frame(
            x = colnames(normalized_counts),
            y = normalized_counts[gene_id, ],
            color = metadata[[color]]) %>%
            ggplot(
                aes_(x = ~x,
                     y = ~y,
                     color = ~color,
                     shape = ~color)
            ) +
            ggtitle(paste(gene_name, gene_id, sep = label_sep)) +
            geom_point(size = 4) +
            theme(
                axis.text.x = element_text(angle = 90)
            ) +
            labs(x = "sample",
                 y = ylab,
                 fill = "") +
            expand_limits(y = 0)
        show(plot)
    }) %>% invisible
}



#' Plot principal component analysis (PCA)
#'
#' Wrapper for [DESeq2::plotPCA()] that improves PCA sample coloring and
#' labeling.
#'
#' @param bcb [bcbioRnaDataSet].
#' @param dt [DESeqTransform] generated from [rlog()] (**recommended**) or
#'   [vst()] on a [DESeqDataSet].
#' @param genes Character vector of gene identifiers to use.
#' @param interesting_groups Interesting groups to use for point appearance. If `NULL`,
#'   color defaults to all `interesting_groups` parameters set in [bcbioRnaDataSet].
#' @param shape Make points easier to inspect with differing shapes.
#' @param label Superimpose sample text labels on the plot.
#' @return [ggplot].
#' @export
#'
#' @seealso
#' - [DESeq2::plotPCA()].
#' - [plotPCA source code](https://github.com/Bioconductor-mirror/DESeq2/blob/f48fab3aa01d6f3297eab76b5d59e191eed006fb/R/plots.R).
#' - [Bioconductor thread on `ntop` usage](https://support.bioconductor.org/p/51270/).
plot_pca <- function(
    bcb,
    dt,
    genes = NULL,
    interesting_groups = NULL,
    shape = FALSE,
    label = TRUE) {
    run <- metadata(bcb)
    .check_dt(dt)
    name <- deparse(substitute(dt))

    if (!is.null(genes)) {
        dt <- dt[genes, ]
        # Set ntop to the number of genes requested
        ntop <- length(genes)
    } else {
        # Recommended DESeq default
        ntop <- 500
    }
    if (is.null(interesting_groups)) {
        interesting_groups <- run$interesting_groups
    }
    interesting_groups_name <- paste(interesting_groups, collapse = " :\n")

    # `group` column is generated by `plotPCA()` using `interesting_groups`
    data <- plotPCA(dt,
                    interesting_groups = interesting_groups,
                    returnData = TRUE,
                    ntop = ntop) %>% snake
    percent_var <- round(100 * attr(data, "percentVar"))

    # Always define color by `interesting_groups`
    data$color <- data$group

    if (isTRUE(shape)) {
        data$shape <- data$group
    } else {
        data$shape <- "default"
    }

    # [TODO] Don't use `@` slot accessor
    data$label <- dt@colData$description

    plot <- ggplot(
        data,
        aes_(x = ~pc1,
             y = ~pc2,
             color = ~color,
             shape = ~shape)
    ) +
        geom_point(size = 3) +
        coord_fixed() +
        labs(title = paste("pca", name, sep = label_sep),
             x = paste0("pc1: ", percent_var[1], "% variance"),
             y = paste0("pc2: ", percent_var[2], "% variance"),
             color = interesting_groups_name,
             shape = interesting_groups_name)

    if (!isTRUE(shape)) {
        plot <- plot + guides(shape = FALSE)
    }

    # Label with sample description, if desired
    if (isTRUE(label)) {
        plot <- plot +
            geom_text_repel(aes_(label = ~label), show.legend = FALSE)
    }

    plot
}
