#' Quickly plot principal component analysis (PCA)
#'
#' @author Michael Steinbaugh
#'
#' @import DESeq2
#' @import ggplot2
#'
#' @param bcbio bcbio list object
#' @param dt \code{DESeqTransform} object generated from \code{rlog()} or
#'   \code{vst()} on a \code{DESeqDataSet} object. We prefer to pipe the
#'   transformed data in to this function because the operation is CPU
#'   intensive, and is slow when applied to multiple PCA plot operations.
#'
#' @return PCA plot
#' @export
#'
#' @examples
#' \dontrun{
#' plot_deseq_pca(rlog)
#' }
plot_deseq_pca <- function(bcbio, dt) {
    if (class(dt)[1] != "DESeqTransform") {
        stop("This function requires a DESeqTransform object.")
    }
    name <- deparse(substitute(dt))

    # Interesting groups define the colors and shapes
    # The `group` column is generated by `plotPCA()` using `intgroup`
    intgroup <- bcbio$intgroup

    # `plotPCA()` uses `ntop = 500` by default
    # To plot all gene variation, use `ntop = nrow(.)`
    data <- DESeq2::plotPCA(dt,
                            intgroup = intgroup,
                            returnData = TRUE)
    percent_var <- round(100 * attr(data, "percentVar"))
    ggplot2::ggplot(data,
                    ggplot2::aes_(x = ~PC1,
                                  y = ~PC2,
                                  color = ~group,
                                  shape = ~group)
    ) +
        ggplot2::ggtitle(paste("pca:", name)) +
        ggplot2::geom_point(size = 3) +
        ggplot2::xlab(paste0("pc1: ", percent_var[1], "% variance")) +
        ggplot2::ylab(paste0("pc2: ", percent_var[2], "% variance")) +
        ggplot2::coord_fixed() +
        ggplot2::labs(color = color, shape = shape)

    # Add `ggrepel` text label support here in the future
}
