#' Plot principal component analysis (PCA)
#'
#' Wrapper for [DESeq2::plotPCA()] that improves PCA sample coloring and
#' labeling.
#'
#' @param run bcbio-nextgen run.
#' @param dt \linkS4class{DESeqTransform} generated from [DESeq2::rlog()] or
#'   [DESeq2::vst()] on a \linkS4class{DESeqDataSet}.
#' @param label Superimpose sample text labels on the plot.
#'
#' @return ggplot2 object.
#' @export
#'
#' @seealso \code{\link[DESeq2]{plotPCA}}
plot_pca <- function(run, dt, label = TRUE) {
    check_run(run)
    check_dt(dt)
    name <- deparse(substitute(dt))

    # Interesting groups define the colors and shapes
    # The `group` column is generated by `plotPCA()` using `intgroup`
    intgroup <- run$intgroup
    color <- "group"
    shape <- intgroup[1]

    # `plotPCA()` uses `ntop = 500` by default
    # To plot all gene variation, use `ntop = nrow(.)`
    data <- plotPCA(dt,
                    intgroup = intgroup,
                    returnData = TRUE)
    percent_var <- round(100 * attr(data, "percentVar"))
    plot <- data.frame(x = data$PC1,
                       y = data$PC2,
                       color = data[[color]],
                       shape = data[[shape]],
                       label = dt@colData$description) %>%
        ggplot(
            aes_(x = ~x,
                 y = ~y,
                 color = ~color,
                 shape = ~shape)
        ) +
        ggtitle(paste("pca", name, sep = " : ")) +
        geom_point(size = 3) +
        coord_fixed() +
        labs(x = paste0("pc1: ", percent_var[1], "% variance"),
             y = paste0("pc2: ", percent_var[2], "% variance"),
             color = "color",
             shape = "shape")

    # Label with sample description, if desired
    if (isTRUE(label)) {
        plot <- plot +
            geom_text_repel(aes_(label = ~label))
    }

    plot
}
