#' Plot an individual gene
#'
#' @author Michael Steinbaugh
#'
#' @param run [bcbioRnaDataSet].
#' @param normalized_counts Normalized counts matrix. Can be obtained from
#'   [DESeqDataSet] using [counts()] with `normalized = TRUE)`. Transcripts per
#'   million (TPM) are also acceptable.
#' @param gene Gene identifier. Can input multiple genes as a character vector.
#' @param format Ensembl identifier format. Defaults to the gene name (symbol).
#'
#' @export
plot_gene <- function(
    run,
    normalized_counts,
    gene,
    format = "external_gene_name") {
    check_run(run)

    color <- run$intgroup[1]
    ylab <- deparse(substitute(normalized_counts))
    metadata <- run$metadata

    # Match unique gene identifier with name (gene symbol) using the internally
    # stored Ensembl annotations saved in the run object
    match <- run$ensembl %>%
        .[.[[format]] %in% gene, ] %>%
        .[order(.$external_gene_name), ]

    # Seq along Ensembl data frame here instead of the gene input vector,
    # which will then output only genes that match Ensembl
    lapply(1:nrow(match), function(a) {
        gene_name <- match$external_gene_name[[a]]
        gene_id <- match$ensembl_gene_id[[a]]
        plot <- data.frame(
            x = colnames(normalized_counts),
            y = normalized_counts[gene_id, ],
            color = metadata[[color]]) %>%
            ggplot(
                aes_(x = ~x,
                     y = ~y,
                     color = ~color,
                     shape = ~color)
            ) +
            ggtitle(paste(gene_name, gene_id, sep = " : ")) +
            geom_point(size = 4) +
            theme(
                axis.text.x = element_text(angle = 90)
            ) +
            labs(x = "sample",
                 y = ylab,
                 fill = "") +
            expand_limits(y = 0)
        show(plot)
    }) %>% invisible
}



#' Plot principal component analysis (PCA)
#'
#' Wrapper for [DESeq2::plotPCA()] that improves PCA sample coloring and
#' labeling.
#'
#' @param run [bcbioRnaDataSet].
#' @param dt [DESeqTransform] generated from [rlog()] (**recommended**) or
#'   [vst()] on a [DESeqDataSet].
#' @param label Superimpose sample text labels on the plot.
#' @param ntop Number of genes to use for PCA. To plot all gene variation, use
#'   `ntop = nrow(.)`. Note that using all genes for PCA is generally *not
#'   recommended*.
#' @return [ggplot].
#' @export
#'
#' @seealso
#' - [DESeq2::plotPCA()].
#' - [Bioconductor thread on `ntop` usage](https://support.bioconductor.org/p/51270/).
plot_pca <- function(run, dt, label = TRUE, ntop = 500) {
    check_run(run)
    check_dt(dt)
    name <- deparse(substitute(dt))

    # Interesting groups define the colors and shapes
    # The `group` column is generated by `plotPCA()` using `intgroup`
    intgroup <- run$intgroup
    color <- "group"
    shape <- intgroup[1]

    data <- plotPCA(dt, intgroup = intgroup,
                    returnData = TRUE, ntop = ntop)
    percent_var <- round(100 * attr(data, "percentVar"))

    plot <- data.frame(x = data$PC1,
                       y = data$PC2,
                       color = data[[color]],
                       shape = data[[shape]],
                       label = dt@colData$description) %>%
        ggplot(
            aes_(x = ~x,
                 y = ~y,
                 color = ~color,
                 shape = ~shape)
        ) +
        ggtitle(paste("pca", name, sep = " : ")) +
        geom_point(size = 3) +
        coord_fixed() +
        labs(x = paste0("pc1: ", percent_var[1], "% variance"),
             y = paste0("pc2: ", percent_var[2], "% variance"),
             color = "color",
             shape = "shape")

    # Label with sample description, if desired
    if (isTRUE(label)) {
        plot <- plot +
            geom_text_repel(aes_(label = ~label))
    }

    plot
}
