#' Print top table
#'
#' @author Michael Steinbaugh
#'
#' @importFrom utils head
#'
#' @param res_tables Results tables generated by \code{res_tables()}
#'
#' @return Data frame or kable, depending on the call
#' @export
top_table <- function(res_tables) {
    get_top <- function(df) {
        discard <- c("description",
                     "lfc_se",
                     "pvalue",
                     "stat")
        df[, setdiff(colnames(df), discard)] %>%
            utils::head(n = 50)
    }

    caption_prefix <- paste0(
        res_tables$name, ": ", res_tables$contrast)

    # Upregulated
    up <- get_top(res_tables$deg_lfc_up)
    kable(up, caption = paste(caption_prefix,
                              "top upregulated genes",
                              sep = " : "))

    # Downregulated
    down <- get_top(res_tables$deg_lfc_down)
    kable(down, caption = paste(caption_prefix,
                                "top downregulated genes",
                                sep = " : "))
}
