#' Top tables of differential expression results.
#'
#' @author Michael Steinbaugh
#'
#' @param res_tbl Results tables generated by \code{\link{res_tables}}.
#'
#' @return Top tables list.
#' @export
top_tables <- function(res_tbl) {
    subset_top <- function(df) {
        discard <- c("description", "lfc_se", "pvalue", "stat")
        df <- df[, setdiff(colnames(df), discard)] %>%
            remove_rownames %>%
            head(n = 50)

        # Handle digits
        df$base_mean <- round(df$base_mean)
        df$log2_fold_change <- format(df$log2_fold_change, digits = 3)
        df$padj <- format(df$padj, digits = 3, scientific = TRUE)

        return(df)
    }

    up <- subset_top(res_tbl$deg_lfc_up)
    down <- subset_top(res_tbl$deg_lfc_down)

    # Captions
    name <- res_tbl$name
    contrast <- res_tbl$contrast
    sep <- " : "
    name_prefix <- paste(name, contrast, sep = sep)

    show(kable(up, caption = paste(name_prefix, "upregulated", sep = sep)))
    show(kable(down, caption = paste(name_prefix, "downregulated", sep = sep)))
}
