#' Top tables of differential expression results
#'
#' @author Michael Steinbaugh
#'
#' @importFrom utils head
#'
#' @param res_tables Results tables generated by \code{res_tables()}
#'
#' @return Data frame or kable, depending on the call
#' @export
top_tables <- function(res_tables) {
    subset_top <- function(df) {
        discard <- c("description", "lfc_se", "pvalue", "stat")
        df[, setdiff(colnames(df), discard)] %>% head(n = 50)
    }

    up <- subset_top(res_tables$deg_lfc_up)
    down <- subset_top(res_tables$deg_lfc_down)

    sep <- " : "
    name_prefix <- paste(res_tables$name,
                         res_tables$contrast,
                         sep = sep)

    list <- list(up = up, down = down)
    names(list) <- c(paste(name_prefix, "upregulated", sep = sep),
                     paste(name_prefix, "downregulated", sep = sep))

    return(list)
}
