#' Top Tables of Differential Expression Results
#'
#' @author Michael Steinbaugh
#'
#' @param resTbl DESeq2 results tables list generated by [resultsTables()].
#' @param n Number genes to report.
#' @param coding Whether to only return coding genes.
#'
#' @return Top table kables, for knit report.
#' @export
topTables <- function(
    resTbl,
    n = 50L,
    coding = FALSE) {
    subsetTop <- function(df) {
        if (isTRUE(coding)) {
            df <- df %>%
                .[.[["broadClass"]] == "coding", ]
        }
        df %>%
            head(n = n) %>%
            mutate(
                baseMean = round(.data[["baseMean"]]),
                log2FoldChange = format(.data[["log2FoldChange"]],
                                        digits = 3L),
                padj = format(.data[["padj"]],
                              digits = 3L,
                              scientific = TRUE)) %>%
            .[, c("ensgene", "baseMean", "log2FoldChange", "padj",
                  "symbol", "biotype")] %>%
            remove_rownames
    }

    up <- subsetTop(resTbl[["degLFCUp"]])
    down <- subsetTop(resTbl[["degLFCDown"]])

    # Captions
    name <- resTbl[["name"]]
    contrast <- resTbl[["contrast"]]
    namePrefix <- paste(name, contrast, sep = labelSep)

    show(kable(
        up,
        caption = paste(namePrefix, "upregulated", sep = labelSep)))
    show(kable(
        down,
        caption = paste(namePrefix, "downregulated", sep = labelSep)))
}
